[project]
name = "unlimited-ai-video-mcp"
description = "Unlimited AI Video MCP server utilizing remote compute (Beam, Kaggle, Hugging Face) for high-performance AI video generation."
version = "2.0.0"
license = {file = "LICENSE"}
dependencies = ["requests==2.32.3", "configparser==7.1.0", "numpy==2.1.1", "torch"]

[project.urls]
Repository = "https://github.com/khs0927/ComfyUI-API"
